# Expose your documentation as JSON swagger compliant
app_swagger:
    path: /api/doc.json
    methods: GET
    controller: nelmio_api_doc.controller.swagger

# Expose your documentation as YAML swagger compliant
app_swagger_yaml:
    path: /api/doc.yaml
    methods: GET
    controller: nelmio_api_doc.controller.swagger
    defaults:
        format: yaml

# Expose your documentation with Swagger UI
app_swagger_ui:
    path: /api/docs
    methods: GET
    controller: nelmio_api_doc.controller.swagger_ui